/**
 * File generated from the Auteur uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package fr.bermosa.domain;

import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;

import org.springframework.roo.addon.javabean.RooJavaBean;
import org.springframework.roo.addon.jpa.activerecord.RooJpaActiveRecord;
import org.springframework.roo.addon.tostring.RooToString;

import java.util.HashSet;
import java.util.Set;
import java.util.Date;

// Start of user code (imports)
import org.springframework.format.annotation.DateTimeFormat;
// End of user code

@RooJavaBean
@RooToString(excludeFields = { "creerPar", "livresAuteurs", "modifierPar" })
@RooJpaActiveRecord(sequenceName = "SEQ_AUTEUR", finders = {
// Start of user code (finders)
// End of user code
})
// Start of user code - annotations for Auteur
// End of user code
public class Auteur {

	@NotNull
	// Start of user code - annotations for prenom
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private String prenom;
	
	@NotNull
	// Start of user code - annotations for nom
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private String nom;
	
	@DateTimeFormat(style="S-")
	// Start of user code - annotations for dtModification
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Date dtModification;
	
	@DateTimeFormat(style="S-")
	@NotNull
	// Start of user code - annotations for dtCreation
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Date dtCreation = new Date();
	
	@DateTimeFormat(style="S-")
	// Start of user code - annotations for dtFinUsage
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Date dtFinUsage;
	
	@NotNull
	@ManyToOne
	// Start of user code - annotations for creerPar
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Acteur creerPar;
	
	@OneToMany(mappedBy="auteur")
	// Start of user code - annotations for livresAuteurs
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Set<LivresAuteurs> livresAuteurs = new HashSet<LivresAuteurs>();
	
	@ManyToOne
	// Start of user code - annotations for modifierPar
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Acteur modifierPar;

}
