/**
 * File generated from the Chapitre uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package fr.bermosa.domain;

import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderColumn;
import javax.validation.constraints.NotNull;

import org.springframework.roo.addon.javabean.RooJavaBean;
import org.springframework.roo.addon.jpa.activerecord.RooJpaActiveRecord;
import org.springframework.roo.addon.tostring.RooToString;

import java.util.LinkedHashSet;
import java.util.Set;
import java.util.Date;

// Start of user code (imports)
import org.springframework.format.annotation.DateTimeFormat;
// End of user code

@RooJavaBean
@RooToString(excludeFields = { "creerPar", "livre", "modifierPar", "parties" })
@RooJpaActiveRecord(sequenceName = "SEQ_CHAPITRE", finders = {
// Start of user code (finders)
// End of user code
})
// Start of user code - annotations for Chapitre
// End of user code
public class Chapitre {

	@DateTimeFormat(style="S-")
	// Start of user code - annotations for dtModification
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Date dtModification;
	
	@NotNull
	// Start of user code - annotations for titre
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private String titre;
	
	@DateTimeFormat(style="S-")
	@NotNull
	// Start of user code - annotations for dtCreation
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Date dtCreation = new Date();
	
	@NotNull
	// Start of user code - annotations for resume
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private String resume;
	
	@NotNull
	@ManyToOne
	// Start of user code - annotations for creerPar
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Acteur creerPar;
	
	@NotNull
	@ManyToOne
	// Start of user code - annotations for livre
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Livre livre;
	
	@ManyToOne
	// Start of user code - annotations for modifierPar
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Acteur modifierPar;
	
	@OrderColumn
	@OneToMany(mappedBy="chapitre")
	// Start of user code - annotations for parties
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Set<Partie> parties = new LinkedHashSet<Partie>();

}
