// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fr.bermosa.domain;

import fr.bermosa.domain.Groupe;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Groupe_Roo_Configurable {
    
    declare @type: Groupe: @Configurable;
    
}
