/**
 * File generated from the Livre uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package fr.bermosa.domain;

import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderColumn;
import javax.validation.constraints.NotNull;

import org.springframework.roo.addon.javabean.RooJavaBean;
import org.springframework.roo.addon.jpa.activerecord.RooJpaActiveRecord;
import org.springframework.roo.addon.tostring.RooToString;

import java.util.LinkedHashSet;
import java.util.Set;
import java.util.HashSet;
import java.util.Set;
import java.util.Date;

// Start of user code (imports)
import org.springframework.format.annotation.DateTimeFormat;
// End of user code

@RooJavaBean
@RooToString(excludeFields = { "chapitres", "creerPar", "livresAuteurs", "livresEditions", "livresGroupes", "modifierPar" })
@RooJpaActiveRecord(sequenceName = "SEQ_LIVRE", finders = {
// Start of user code (finders)
// End of user code
})
// Start of user code - annotations for Livre
// End of user code
public class Livre {

	@NotNull
	// Start of user code - annotations for titre
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private String titre;
	
	@DateTimeFormat(style="S-")
	@NotNull
	// Start of user code - annotations for dtSortie
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Date dtSortie;
	
	@NotNull
	// Start of user code - annotations for isbn
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private String isbn;
	
	@DateTimeFormat(style="S-")
	// Start of user code - annotations for dtModification
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Date dtModification;
	
	@DateTimeFormat(style="S-")
	@NotNull
	// Start of user code - annotations for dtCreation
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Date dtCreation = new Date();
	
	@DateTimeFormat(style="S-")
	// Start of user code - annotations for dtFinUsage
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Date dtFinUsage;
	
	@OrderColumn
	@OneToMany(mappedBy="livre")
	// Start of user code - annotations for chapitres
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Set<Chapitre> chapitres = new LinkedHashSet<Chapitre>();
	
	@NotNull
	@ManyToOne
	// Start of user code - annotations for creerPar
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Acteur creerPar;
	
	@OneToMany(mappedBy="livre")
	// Start of user code - annotations for livresAuteurs
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Set<LivresAuteurs> livresAuteurs = new HashSet<LivresAuteurs>();
	
	@OneToMany(mappedBy="livre")
	// Start of user code - annotations for livresEditions
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Set<LivresEditions> livresEditions = new HashSet<LivresEditions>();
	
	@OneToMany(mappedBy="livre")
	// Start of user code - annotations for livresGroupes
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Set<LivresGroupes> livresGroupes = new HashSet<LivresGroupes>();
	
	@ManyToOne
	// Start of user code - annotations for modifierPar
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Acteur modifierPar;

}
