/**
 * File generated from the LivresGroupes uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package fr.bermosa.domain;

import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;

import org.springframework.roo.addon.javabean.RooJavaBean;
import org.springframework.roo.addon.jpa.activerecord.RooJpaActiveRecord;
import org.springframework.roo.addon.tostring.RooToString;

import java.util.HashSet;
import java.util.Set;
import java.util.Date;

// Start of user code (imports)
import org.springframework.format.annotation.DateTimeFormat;
// End of user code

@RooJavaBean
@RooToString(excludeFields = { "groupe", "livre" })
@RooJpaActiveRecord(sequenceName = "SEQ_LIVRESGROUPES", finders = {
// Start of user code (finders)
// End of user code
})
// Start of user code - annotations for LivresGroupes
// End of user code
public class LivresGroupes {

	@DateTimeFormat(style="S-")
	// Start of user code - annotations for dtFinUsage
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Date dtFinUsage;
	
	@DateTimeFormat(style="S-")
	@NotNull
	// Start of user code - annotations for dtCreation
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Date dtCreation = new Date();
	
	@NotNull
	@ManyToOne
	// Start of user code - annotations for groupe
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Groupe groupe;
	
	@NotNull
	@ManyToOne
	// Start of user code - annotations for livre
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Livre livre;

}
