// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fr.bermosa.domain;

import fr.bermosa.domain.Livre;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Livre_Roo_Configurable {
    
    declare @type: Livre: @Configurable;
    
}
