/**
 * File generated from the Partie uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package fr.bermosa.domain;

import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;

import org.springframework.roo.addon.javabean.RooJavaBean;
import org.springframework.roo.addon.jpa.activerecord.RooJpaActiveRecord;
import org.springframework.roo.addon.tostring.RooToString;

import java.util.LinkedHashSet;
import java.util.Set;
import java.util.Date;

// Start of user code (imports)
import org.springframework.format.annotation.DateTimeFormat;
// End of user code

@RooJavaBean
@RooToString(excludeFields = { "chapitre", "creerPar", "modifierPar" })
@RooJpaActiveRecord(sequenceName = "SEQ_PARTIE", finders = {
// Start of user code (finders)
// End of user code
})
// Start of user code - annotations for Partie
// End of user code
public class Partie {

	@DateTimeFormat(style="S-")
	@NotNull
	// Start of user code - annotations for dtCreation
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Date dtCreation = new Date();
	
	@NotNull
	// Start of user code - annotations for titre
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private String titre;
	
	@NotNull
	// Start of user code - annotations for resume
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private String resume;
	
	@DateTimeFormat(style="S-")
	// Start of user code - annotations for dtModification
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Date dtModification;
	
	@NotNull
	@ManyToOne
	// Start of user code - annotations for chapitre
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Chapitre chapitre;
	
	@NotNull
	@ManyToOne
	// Start of user code - annotations for creerPar
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Acteur creerPar;
	
	@ManyToOne
	// Start of user code - annotations for modifierPar
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Acteur modifierPar;

}
