/**
 * File generated from the Role uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */
package fr.bermosa.domain;

import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;

import org.springframework.roo.addon.javabean.RooJavaBean;
import org.springframework.roo.addon.jpa.activerecord.RooJpaActiveRecord;
import org.springframework.roo.addon.tostring.RooToString;

import java.util.HashSet;
import java.util.Set;
import java.util.Date;

// Start of user code (imports)
import org.springframework.format.annotation.DateTimeFormat;
// End of user code

@RooJavaBean
@RooToString(excludeFields = { "acteur" })
@RooJpaActiveRecord(sequenceName = "SEQ_ROLE", finders = {
// Start of user code (finders)
// End of user code
})
// Start of user code - annotations for Role
// End of user code
public class Role {

	@NotNull
	// Start of user code - annotations for role
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private String role = "ROLE_USER";
	
	@DateTimeFormat(style="S-")
	@NotNull
	// Start of user code - annotations for dtCreation
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Date dtCreation = new Date();
	
	@NotNull
	@ManyToOne
	// Start of user code - annotations for acteur
	// ex: @JoinTable(name="CUST_PHONES")
	// End of user code
	private Acteur acteur;

}
